(() => {
const pairs = {
'跳至主要內容':'Skip to content','用畫筆創作，讓角色動起來。':'Illustrated with care. Brought to life.','首頁':'Home','建模':'Rigging','繪圖':'Model art','插畫':'Illustration','讓你的角色，':'Your character,','擁有生命。':'brought to life.','你好，我是 Kana。':'Hi, I’m Kana.','提供 Live2D 建模、立繪拆圖及插畫委託服務。':'I create Live2D rigging, layered model art and illustrations.','歡迎個人與商業合作洽詢。':'Personal and commercial inquiries are welcome.','探索作品 ↗':'Explore my work ↗','聯絡委託 →':'Commission inquiry →','創作與作品':'A world of characters','從一張插畫，到每個細微的表情。':'From the first illustration to the smallest expression.','細膩的動作，鮮活的表情。':'Thoughtful motion. Expressive characters.','為你的角色，畫下第一個樣子。':'The first chapter of your character.','把喜歡的瞬間，留在畫裡。':'Little moments, made into art.',
'委託流程':'Commission process','討論需求':'Tell me your idea','確認項目、用途、報價及交期。':'We confirm the scope, usage, quote and timeline.','付款與排單':'Payment & booking','確認付款安排後排單。':'Your slot is booked after payment arrangements are confirmed.','製作與確認':'Create & refine','繪圖依草圖、線稿、上色確認。':'Review the sketch, line art and colors as your artwork develops.','交付作品':'Your finished work','完稿確認及付清後，透過 Google Drive 交付。':'After final approval and full payment, receive your files via Google Drive.',
'聯絡委託':'Commission inquiries','付款方式':'Payment methods','其他連結 ↗':'More links ↗','MYR：本地銀行、TNG、Gank':'MYR: local bank transfer, TNG, Gank','USD／TWD：Gank、VGen':'USD / TWD: Gank, VGen','MYR 適用於馬來西亞客戶。':'MYR is available for clients in Malaysia.','USD／TWD 適用於海外客戶。':'USD / TWD are available for international clients.','委託須知':'Commission terms','接單與修改':'Acceptance & revisions','保留接受或拒絕委託的權利。每件作品包含最多 3 次修改；超出次數或大幅修改另收費。':'I reserve the right to accept or decline a commission. Each piece includes up to 3 revisions; additional revisions or major changes cost extra.','付款與取消':'Payment & cancellations','付清全款後交付作品。若委託人因個人因素取消，已付定金或款項不退還。付款及排單安排請於委託前確認。':'Final files are delivered after full payment. Deposits and payments are non-refundable if the client cancels for personal reasons. Please confirm payment and scheduling arrangements before commissioning.','使用範圍':'Usage rights','可用於直播、影片封面及社群宣傳。用於實體或數位商品販售，價格按原價 2 倍計算。不得轉賣委託作品。':'You may use the work for livestreams, video covers and social media promotion. Use for physical or digital merchandise sales costs 2× the original price. Reselling the commissioned work is prohibited.','AI 使用限制':'AI restrictions','禁止將委託作品用於 AI 訓練、生成或相關用途。':'Commissioned work may not be used for AI training, generation or related purposes.','作品展示與署名':'Portfolio & credit','作品可用於作者的作品集、個人網站及社群宣傳。歡迎於使用時標註作者。':'I may display the work in my portfolio, on my website and on social media. Credit is appreciated when using the work.','交付檔案':'Deliverables','Live2D 建模不提供 cmo3。插畫按項目交付 PNG。Live2D 立繪拆圖的 PSD 交付內容請於委託前確認。':'Live2D rigging does not include the cmo3 source file. Illustrations are delivered as PNG according to the service. Please confirm PSD deliverables for layered Live2D art before commissioning.',
'幣別':'Currency','建模價格':'Rigging prices','簡易建模':'Simple rig','普通建模':'Regular rig','不提供 cmo3 原工作檔。工期請於委託前確認。':'The cmo3 source file is not included. Please confirm the timeline before commissioning.','加購項目':'Add-ons','靜態表情':'Static expression','動態表情':'Animated expression','額外服裝或髮型':'Extra outfit or hairstyle','額外動作或配件':'Extra pose or accessory','包含內容':'What’s included','頭部及身體 XYZ':'Head & body XYZ','頭髮、眼珠物理':'Hair & eye physics','呼吸動作':'Breathing animation','2 個靜態按鍵表情':'2 static expression hotkeys','簡易與普通建模的差別':'Simple vs. regular rig','簡易：3×3 嘴型、同方向物理。':'Simple: 3×3 mouth shapes and same-direction physics.','普通：獨立物理。嘴型規格依委託內容確認。':'Regular: independent physics. Mouth specifications are confirmed for each commission.','下方為建模作品展示。':'Explore my rigging work below.','建模作品':'Rigging showcase',
'立繪拆圖價格':'Layered model art prices','可愛模板':'Cute template','簡易版':'Simple version','普通版':'Regular version','工期與 PSD 交付內容請於委託前確認。':'Please confirm the timeline and PSD deliverables before commissioning.','表情':'Expression','髮型':'Hairstyle','服裝':'Outfit','小配件':'Small accessory','大配件':'Large accessory','角色設計':'Character design','小改':'Minor revision','大改':'Major revision','版本說明':'Version details','單層上色，拆圖 50 層以內。':'Single-layer coloring, separated into up to 50 layers.','2 層上色，拆圖 50 層以內。':'Two-layer coloring, separated into up to 50 layers.','可選上色層數，或交由繪師安排。拆圖 100 層以上。':'Choose your coloring layers or leave them to the artist. Separated into more than 100 layers.','立繪作品':'Model art showcase','繪圖・立繪拆圖':'Layered character art','插畫繪圖':'Character illustrations',
'插畫價格':'Illustration prices','Q 版':'Chibi','正比':'Standard proportions','頭像':'Portrait','全身':'Full body','半身':'Half body','2–4 星期，不含背景，交付 PNG。':'2–4 weeks. No background. Delivered as PNG.','其他項目':'Other services','三視圖':'Three-view character sheet','貼圖':'Emote','以上項目：2–4 星期，不含背景，交付 PNG。':'The above services take 2–4 weeks, exclude backgrounds and are delivered as PNG.','全身立繪拆圖':'Layered full-body art','2–3 個月。':'2–3 months.','Q 版待機畫面（已拆圖）':'Layered chibi waiting screen','1–2 個月。':'1–2 months.','修改費用':'Revision fees','插畫作品':'Illustration showcase','各幣別價格為獨立標價。實際費用依委託內容報價。':'Prices are set independently for each currency. Your final quote depends on the commission scope.','有個角色，想讓它成真？':'Have a character in mind?','一起把你的想像變成作品。':'Let’s turn your imagination into something you can share.','聊聊你的想法 ↗':'Let’s talk about it ↗',
'普通建模展示':'Regular rig showcase','企鵝模型':'Penguin model','黑貓模型':'Black cat model','Q 版角色':'Chibi character','Kana 模型':'Kana model','角色模型作品':'Character model','Kana 立繪':'Kana character art','Q 版頭像':'Chibi portrait','正比頭像':'Character portrait','正比全身':'Full-body character','Q 版待機畫面':'Chibi waiting screen','關閉 ×':'Close ×','另開影片 ↗':'Open video ↗','▶ 播放影片':'▶ Play video','開啟原始作品':'Open original artwork','Kana 的角色插畫':'Kana character illustration','作品圖片':'Artwork preview','主選單':'Main navigation','kkana 委託網站':'Kana commission portfolio'
};
let lang='zh';try{if(localStorage.getItem('kk-language')==='en')lang='en';}catch{}
const originals=new WeakMap();
function t(text){return lang==='en'?(pairs[text]||text):text;}
function apply(){
 document.documentElement.lang=lang==='en'?'en':'zh-Hant';
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
 while(walker.nextNode()){
 const node=walker.currentNode;if(node.parentElement.closest('script,style,noscript,[data-lang],[data-prices]'))continue;
 let saved=originals.get(node);if(!saved||node.nodeValue!==saved.last)saved={original:node.nodeValue};
 const trimmed=saved.original.trim();const next=saved.original.replace(trimmed,t(trimmed));if(node.nodeValue!==next)node.nodeValue=next;saved.last=next;originals.set(node,saved);
 }
 document.querySelectorAll('[aria-label],[alt]').forEach(el=>{for(const attr of ['aria-label','alt']){if(!el.hasAttribute(attr))continue;const key='original'+attr.replace('-','');if(!el.dataset[key])el.dataset[key]=el.getAttribute(attr);let value=el.dataset[key];if(lang==='en'){if(value.startsWith('放大 '))value='Enlarge '+t(value.slice(3));else if(value.startsWith('播放 '))value='Play '+t(value.slice(3));else value=t(value);}el.setAttribute(attr,value);}});
 document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));
}
window.KK_I18N={t,apply,get lang(){return lang;}};
document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{lang=button.dataset.lang;try{localStorage.setItem('kk-language',lang);}catch{}window.dispatchEvent(new Event('kk-language-change'));apply();}));
})();
